"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Badge, Badges } from "../components/Badge";
import { InlineSelect } from "../components/InlineSelect";
import { ErrorBanner } from "../components/ErrorBanner";
import { RunsPanel } from "../components/RunsPanel";
import { TOPICS, IDEA_STATUS, IDEA_EFFORT, IDEA_FORMAT_CATEGORY } from "@/lib/schema";

export default function IdeasPage() {
  const [rows, setRows] = useState<any[]>([]);
  const [jobs, setJobs] = useState<any[]>([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const [q, setQ] = useState("");
  const [topic, setTopic] = useState("All");
  const [category, setCategory] = useState("All");
  const [status, setStatus] = useState("All");
  const [detail, setDetail] = useState<any>(null);

  const [genTopic, setGenTopic] = useState(TOPICS[0]);
  const [generating, setGenerating] = useState(false);
  const jobsRef = useRef<any[]>([]);

  async function load() {
    try {
      const d = await (await fetch("/api/ideas")).json();
      if (d.error) setError(d.error);
      else setRows(d.rows);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }
  async function loadJobs() {
    try {
      const d = await (await fetch("/api/run")).json();
      const ideaJobs = (d.jobs || []).filter((j: any) => j.kind === "ideas");
      jobsRef.current = ideaJobs;
      setJobs(ideaJobs);
    } catch {}
  }

  useEffect(() => {
    load();
    loadJobs();
    const t = setInterval(async () => {
      const wasRunning = jobsRef.current.some((j) => j.status === "running");
      await loadJobs();
      // A finished idea run means new rows may have landed — refresh the list.
      if (wasRunning) load();
    }, 3500);
    return () => clearInterval(t);
  }, []);

  const topicRunning = jobs.some(
    (j) => j.status === "running" && j.topic?.trim().toLowerCase() === genTopic.trim().toLowerCase()
  );

  async function generate() {
    setGenerating(true);
    setError("");
    try {
      const res = await fetch("/api/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "ideas", topic: genTopic }),
      });
      const d = await res.json();
      if (!res.ok) setError(d.error || "Failed to start idea generation.");
      await loadJobs();
    } finally {
      setGenerating(false);
    }
  }

  const shown = useMemo(() => {
    return rows.filter((r) => {
      const p = r.props;
      if (topic !== "All" && !(p.Topic || []).some((t: any) => t.name === topic)) return false;
      if (category !== "All" && p["Format Category"]?.name !== category) return false;
      if (status !== "All" && p.Status?.name !== status) return false;
      if (q) {
        const hay = `${p.Idea || ""} ${p.Concept || ""} ${p["Hook / Angle"] || ""}`.toLowerCase();
        if (!hay.includes(q.toLowerCase())) return false;
      }
      return true;
    });
  }, [rows, topic, category, status, q]);

  return (
    <div>
      <h1>Content Ideas</h1>
      <p className="subtitle">
        On-demand ideas generated by the idea-agent from your VERIFIED / VERIFIED_WITH_CAVEATS findings — digital
        products, plus Instagram/Facebook posts and short-form video. Ideas are written to Notion; edit and shortlist
        them here.
      </p>
      {error && <ErrorBanner message={error} />}

      <div className="toolbar">
        <select value={genTopic} onChange={(e) => setGenTopic(e.target.value)}>
          {TOPICS.map((t) => (
            <option key={t}>{t}</option>
          ))}
        </select>
        <button onClick={generate} disabled={generating || topicRunning} title="Generate ideas from verified findings for this topic">
          {topicRunning ? "Generating…" : generating ? "Starting…" : "✦ Generate ideas"}
        </button>
        <div className="spacer" />
        <span className="muted">
          Reads only VERIFIED / VERIFIED_WITH_CAVEATS findings for the topic.
        </span>
      </div>

      <div className="toolbar">
        <input placeholder="Search ideas…" value={q} onChange={(e) => setQ(e.target.value)} style={{ minWidth: 220 }} />
        <select value={topic} onChange={(e) => setTopic(e.target.value)}>
          <option>All</option>
          {TOPICS.map((t) => (
            <option key={t}>{t}</option>
          ))}
        </select>
        <select value={category} onChange={(e) => setCategory(e.target.value)}>
          <option>All</option>
          {IDEA_FORMAT_CATEGORY.map((c) => (
            <option key={c}>{c}</option>
          ))}
        </select>
        <select value={status} onChange={(e) => setStatus(e.target.value)}>
          <option>All</option>
          {IDEA_STATUS.map((s) => (
            <option key={s}>{s}</option>
          ))}
        </select>
        <span className="muted">{shown.length} shown</span>
      </div>

      <div className="panel">
        <table>
          <thead>
            <tr>
              <th style={{ width: "40%" }}>Idea</th>
              <th>Topic</th>
              <th>Format</th>
              <th>Effort</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {shown.map((r) => (
              <tr key={r.id} style={{ cursor: "pointer" }}>
                <td className="title-cell" onClick={() => setDetail(r)}>
                  {r.props.Idea || <span className="muted">Untitled</span>}
                  {r.props["Hook / Angle"] && (
                    <div className="muted" style={{ fontWeight: 400, fontSize: 12, marginTop: 2 }}>
                      {r.props["Hook / Angle"]}
                    </div>
                  )}
                </td>
                <td onClick={() => setDetail(r)}>
                  <Badges values={r.props.Topic} />
                </td>
                <td onClick={() => setDetail(r)}>
                  <Badge value={r.props["Product Format"]} />
                </td>
                <td onClick={() => setDetail(r)}>
                  <Badge value={r.props.Effort} />
                </td>
                <td>
                  <InlineSelect
                    apiBase="/api/ideas"
                    id={r.id}
                    field="Status"
                    value={r.props.Status?.name || null}
                    options={IDEA_STATUS}
                  />
                </td>
              </tr>
            ))}
            {!loading && shown.length === 0 && (
              <tr>
                <td colSpan={5} className="empty">
                  No ideas yet. Pick a topic above and hit “Generate ideas.”
                </td>
              </tr>
            )}
            {loading && (
              <tr>
                <td colSpan={5} className="empty">
                  Loading…
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <RunsPanel jobs={jobs} title="Idea runs" />

      {detail && <IdeaDetail row={detail} onClose={() => setDetail(null)} />}
    </div>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="field" style={{ marginBottom: 10 }}>
      <label>{label}</label>
      <div>{children}</div>
    </div>
  );
}

function IdeaDetail({ row, onClose }: { row: any; onClose: () => void }) {
  const p = row.props;
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h2>{p.Idea || "Idea"}</h2>
        <div className="badges" style={{ marginBottom: 16 }}>
          <Badge value={p["Format Category"]} />
          <Badge value={p["Product Format"]} />
          <Badge value={p.Status} />
          <Badge value={p.Effort} />
        </div>
        {p.Topic?.length > 0 && (
          <Row label="Topic">
            <Badges values={p.Topic} />
          </Row>
        )}
        {p["Hook / Angle"] && <Row label="Hook / angle">{p["Hook / Angle"]}</Row>}
        {p.Concept && <Row label="Concept">{p.Concept}</Row>}
        {p.Audience && <Row label="Audience">{p.Audience}</Row>}
        {p["Educational Value"] && <Row label="Educational value">{p["Educational Value"]}</Row>}
        {p["Evidence Basis"] && <Row label="Evidence basis">{p["Evidence Basis"]}</Row>}
        <Row label="Source findings">
          {p["Source Findings"]?.length
            ? `${p["Source Findings"].length} linked finding${p["Source Findings"].length === 1 ? "" : "s"} (open in Notion to follow)`
            : "—"}
        </Row>
        <div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 12 }}>
          <a className="link" href={row.url} target="_blank" rel="noreferrer" style={{ alignSelf: "center" }}>
            Open in Notion ↗
          </a>
          <button onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}
